[build]
  command   = "npm run build"   # só para o deploy
  publish   = "dist"
  functions = "netlify/functions"

# Em dev, rode o Vite e faça proxy das Functions
[dev]
  command     = "vite"
  targetPort  = 5173
  port        = 8888
  framework   = "#custom"       # força usar o comando acima

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
